name: darpy
channels:
  - conda-forge
  - darothen
dependencies:
  - cartopy>=0.13
  - dask
  - geopandas
  - jupyter
  - matplotlib
  - netcdf4
  - numpy
  - pyresample
  - python=3.5
  - scipy
  - seaborn>=0.6
  - xlrd
  - xarray>=0.8.2
