name: marc_analysis
channels:
  - unidata
  - IOOS
  - scitools
  - darothen
dependencies:
  - cartopy>=0.12
  - dask
  - geopandas
  - jupyter
  - matplotlib
  - netcdf4
  - numpy
  - python=3.4
  - seaborn>=0.6
  - xlrd
  - xray>=0.6
