name: marc_aie
channels:
  - unidata
  - scitools
  - darothen
dependencies:
  - cartopy>=0.12
  - ipython>=3.2.0
  - ipython-notebook
  - matplotlib
  - netcdf4
  - numpy
  - python=3.4
  - seaborn
  - xlrd
  - xray>=0.5
  - dask
  - windspharm